# 정렬 (Sorting)
데이터를 **크기 순서대로 정렬** 하는 작업이다.
`np.sort()` 를 사용하여 배열을 정렬할 수 있다.

In [1]:
import numpy as np

## 1차원 배열 정렬
`np.sort()`는 배열을 **오름차순** 으로 정렬한다.
원본 배열을 변경하지 않고 **정렬 된 새로운 배열** 을 반환한다.

In [ ]:
arr = np.random.randint(1, 11, 10)
print(arr)

print(np.sort(arr))
print(arr)   # 정렬을 해도, 원본 배열을 변하지 않는다.

[ 2 10  1  4  1 10  8  5  4  4]
[ 1  1  2  4  4  4  5  8 10 10]
[ 2 10  1  4  1 10  8  5  4  4]


## 역순 정렬
슬라이싱 `[::-1]` 을 사용하면 배열을 뒤에서부터 역순으로 뒤집을 수 있다.

In [8]:
np.sort(arr)[::-1]

array([10, 10,  8,  5,  4,  4,  4,  2,  1,  1])

## 2차원 배열 정렬
2차원 배열에서는 `axis` 옵션으로 **정렬 방향** 을 지정할 수 있다.

In [21]:
arr = np.random.randint(1, 15, (3, 4))
print(arr, end="\n---\n")

print(np.sort(arr), end="\n---\n")
print(np.sort(arr, axis=1), end="\n---\n") # axis=1이 기본 값
print(np.sort(arr, axis=0))                # axis=0 행축

[[13  8 11 14]
 [11  3 10 12]
 [12  9 11 13]]
---
[[ 8 11 13 14]
 [ 3 10 11 12]
 [ 9 11 12 13]]
---
[[ 8 11 13 14]
 [ 3 10 11 12]
 [ 9 11 12 13]]
---
[[11  3 10 12]
 [12  8 11 13]
 [13  9 11 14]]


## np.argsort()
배열을 정렬했을 때 **정렬 된 위치(index)** 를 반환한다.
이 인덱스를 이용하면 **다른 배열도 같은 기준으로 정렬** 할 수 있다.

In [23]:
arr = np.array([40, 10, 20, 30])
indices = np.argsort(arr)
print(indices)
arr[indices]

[1 2 3 0]


array([10, 20, 30, 40])

## 역순 정렬
내림차순 정렬은 배열에 `-` 를 붙여 정렬하면 쉽게 구현할 수 있다.

In [24]:
arr = np.array([40, 10, 20, 30])
indices = np.argsort(-arr)
print(indices)
arr[indices]

[0 3 2 1]


array([40, 30, 20, 10])

## 서로 다른 배열을 같은 기준으로 정렬하기

In [27]:
# 학생 이름, 학생 점수 배열
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])

# 점수가 높은 순으로 학생 이름 정렬하기
indices = np.argsort(-scores)
print(indices)
print(names[indices])

[0 3 2 1]
['홍길동' '유관순' '이순신' '신사임당']


In [34]:
# 직접 장성해보기 : 우선순위에 따른 작업 정렬
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])

indices = np.argsort(-priorities)
print(tasks[indices])

['Task D' 'Task E' 'Task A' 'Task C' 'Task B']
