# Indexing | Slicing
- 배열에서 원하는 값을 선택하는 방법이다.
- NumPy는 특정 위치의 값 조회, 특정 구간의 데이터 추출, 조건 기반 데이터 선택 등을 자주 사용한다.

## Indexing
- 배열에서 특정 위치(인덱스) 값을 하나 선택하는 방법이다.
- 파이썬의 list와 동일하게 0부터 시작하며 -1은 마지막 요소를 의미한다.

In [1]:
import numpy as np

In [3]:
# 1차원
arr = np.arange(1, 11)
print(arr)
print(arr[0], arr[1])
print(arr[-1], arr[-2])
print(arr[100]) # IndexError: 인덱스 범위 벗어나면 오류

[ 1  2  3  4  5  6  7  8  9 10]
1 2
10 9


In [7]:
# 2차원
arr1 = np.arange(1, 11)
print(arr1)
arr1 = arr1.reshape(2, 5)
print(arr1)

print(arr1[0][2], arr1[0, 2])  # [행][열], [행, 열] 후자를 더 많이 사용.
print(arr1[1][3], arr1[1, 3])
print(arr1[-1][-2], arr1[-1, -2])

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3 3
9 9
9 9


## Slicing
- 배열에서 특정 구간의 데이터를 잘라서 가져오는 방법이다.
- start : stop : step 형태를 사용하며, stop 위치는 포함되지 않는다.

In [13]:
# 1차원 배열의 슬라이싱: ndarray[start:stop:step]
arr1  = np.arange(1, 11)
print(arr1)
print(arr1[2:7])
print(arr1[2:])
print(arr1[:7])
print(arr1[:-1])
print(arr1[:])
print(arr1[:-2:2])
print(arr1[::-1]) # 역순으로 반환

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7]
[10  9  8  7  6  5  4  3  2  1]


In [17]:
# 2차원 배열 슬라이싱
arr = np.arange(1, 13).reshape(3, 4)
print(arr[:, :], end="\n---\n")    # 모든 행, 모든 열
print(arr[0, :], end="\n---\n")    # 0행에 해당하는 1차원 배열
print(arr[:, 0], end="\n---\n")    # 0열에 해당하는 1차원 배열
print(arr[:, 0:2], end="\n---\n")    # 0열에 해당하는 1차원 배열
print(arr[1:, 2:], end="\n---\n")    # 0열에 해당하는 1차원 배열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
[1 2 3 4]
---
[1 5 9]
---
[[ 1  2]
 [ 5  6]
 [ 9 10]]
---
[[ 7  8]
 [11 12]]
---


## Fancy Indexing
- 여러 개의 특정 위치를 한 번에 선택하는 방법이다.
- 인덱스 리스트를 사용하여 원하는 요소만 추출할 수 있다.

In [19]:
# 1차원
arr = np.linspace(5, 50, 10, dtype=int)  # 5부터 50까지 10개의 숫자를 균등하게 나누어 생성, 정수형으로 반환
print('arr:', arr)
print('arr[[1, 2, 8]]:', arr[[1, 2, 8]])  # 인덱스 리스트를 사용하여 특정 위치의 요소 선택

indexes = [1, 2, 8]
print('arr[indexes]:', arr[indexes])  # 인덱스 리스트를 사용하여 특정 위치의 요소 선택

arr: [ 5 10 15 20 25 30 35 40 45 50]
arr[[1, 2, 8]]: [10 15 45]
arr[indexes]: [10 15 45]


In [27]:
# 2차원
arr = np.linspace(5, 100, 20, dtype=int).reshape(4, 5)
print('arr:\n', arr)

print('arr[0, 1]:', arr[0, 1], end="\n---\n")  # 단일 요소 선택, 좌표 접근 arr[0][1]
print('arr[[0, 1]]:\n', arr[[0, 1]], end="\n---\n")  # 행 인덱스에 리스트를 사용하여 여러 행 선택, 행 선택 - 0, 1행
print('arr[:, [0, 2]]:\n', arr[:, [0, 2]], end="\n---\n") # 열 인덱스에 리스트를 사용하여 여러 열 선택, 열 선택 - 0, 2열

# 행과 열이 모두 리스트면 좌표 선택 - 0행 1열, 1행 3열
print('arr[[0, 1], [1, 3]]:', arr[[0, 1], [1, 3]], end="\n---\n") 

print('arr[[0, 1], 1:4]:\n', arr[[0, 1], 1:4], end="\n---\n")
print('arr[[1, 3], 3:]:\n', arr[[1, 3], 3:], end="\n---\n")
print('arr[[1, 3], -2:]:\n', arr[[1, 3], -2:], end="\n---\n")

arr:
 [[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]
arr[0, 1]: 10
---
arr[[0, 1]]:
 [[ 5 10 15 20 25]
 [30 35 40 45 50]]
---
arr[:, [0, 2]]:
 [[ 5 15]
 [30 40]
 [55 65]
 [80 90]]
---
arr[[0, 1], [1, 3]]: [10 45]
---
arr[[0, 1], 1:4]:
 [[10 15 20]
 [35 40 45]]
---
arr[[1, 3], 3:]:
 [[ 45  50]
 [ 95 100]]
---
arr[[1, 3], -2:]:
 [[ 45  50]
 [ 95 100]]
---


## Boolean Indexing
- 조건식의 결과(True/False)를 이용해서 조건을 만족하는 데이터만 선택하는 방법
- 데이터 분석에서 필터링 할 때 자주 사용 된다

In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[1, 3]])
print(arr[[False, True, False, True, False]])  # 불리언 인덱싱: True인 위치의 요소 선택

print(arr % 2 == 0)
print(arr[arr % 2 == 0])

print(arr > 3)
print(arr[arr > 3])

[2 4]
[2 4]
[False  True False  True False]
[2 4]
[False False False  True  True]
[4 5]


## 3차원 배열
- 배열 안에 배열이 들어있는 구조이다
- 보통 (층, 행, 열) 형태로 접근하며 인덱스는 arr[층, 행, 열] 순서로 사용한다.
- 실제로는 공간이라기보다 다차원 참조 구조라고 이해하는 것이 좋다.

In [32]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]        
    ],
    [
        [7, 8, 9],
        [10, 11, 12]            
    ]
])
print(arr.shape) # "튜플" 형태로 배열의 차원과 각 차원의 크기를 반환
print(arr.ndim)
print(arr.size)
print(arr)

(2, 2, 3)
3
12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
print(arr[0, 0, 1])
print(arr[1, 1, 1])
print(arr[1, 1, 1:])
print(arr[1, :, 1:])
print(arr[:, :, 1:])

2
11
[11 12]
[[ 8  9]
 [11 12]]
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
