# ndarray 연산

## element-wise 연산
- 기본적으로 두 배열은 동일한 shape여야 한다.
- 같은 위치(인덱스)의 요소끼리 연산이 수행 된다.
- 결과 배열 또한 동일한 shape를 가진다.

In [1]:
import numpy as np

arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1, end="\n---\n")

arr2 = np.full_like(arr1, 2)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
print(arr1 + arr2, end="\n---\n")  # 요소별 덧셈
print(arr1 - arr2, end="\n---\n")  # 요소별 뺄셈
print(arr1 * arr2, end="\n---\n")  # 요소별 곱셈
print(arr1 / arr2, end="\n---\n")  # 요소별 나눗셈
print(arr1 // arr2, end="\n---\n")  # 요소별 정수 나눗셈
print(arr1 % arr2, end="\n---\n")  # 요소별 나머지
print(arr1 ** arr2, end="\n---\n")  # 요소별 거듭제곱

## broadcasting 연산 방식
- 두 배열의 shape이 다르면 broadcasting 규칙에 따라 연산이 수행 된다
- 차원이 작은 배열을 자동으로 확장하여 연산이 가능하도록 한다

### 규칙
- 뒤쪽(마지막 차원)부터 shape을 비교
- 두 차원이 같거나, 둘 중 하나가 1이면 연산 가능
- 둘 다 다르고 둘 다 1이 아니면 broadcasting 불가

![](images/broadcasting_example-1.png)
![](images/broadcasting_example-2.png)

In [ ]:
# 브로드캐스트 연산 테스트
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.full((3,), 2)

print(arr1, arr1.shape, end="\n---\n")
print(arr2, arr2.shape, end="\n---\n")

# (2, 3) 배열과 (3,) 배열의 연산
# (3,) -> (1, 3) -> (2, 3)으로 브로드캐스트
print(arr1 + arr2, end="\n---\n")

In [ ]:
arr3 = np.array([1, 2])
print(arr3, arr3.shape)
# ValueError: operands could not be broadcast together with shapes (2,3) (2,) 
# print(arr1 + arr3)  # (2, 3) 배열과 (2,) 배열의 연산 -> 브로드캐스트 불가(ValueError)

In [ ]:
# arr1과 다양한 연산: 결과적으로는 모든 인덱스에 10이 더해졌다.
print(arr1 + 10, end="\n---\n")      # (2, 3) + () 스칼라도 브로드캐스팅 적용
print(arr1 + [10], end="\n---\n")    # (2, 3) + (1,) 리스트도 브로드캐스팅 적용
print(arr1 + [[10]], end="\n---\n")  # (2, 3) + (1, 1) 2차원 리스트도 브로드캐스팅 적용

## 행렬곱셈 Matrix Multiplication
점곱연산 Dot Product (내적)

두 행렬 A B의 곱셈은 첫번째 행렬 A의 행과 두번째 행렬 B의 열간의 곱셈을 수행한다.

조건
- 첫번째 행렬 A의 열의 수와 두번째 행렬 B의 행의 수가 같아야 한다.
- 연산결과는 (첫번째 행렬 A의 행수, 두번째 행렬 B의 열수) 이다.

- **수식**: 행렬 $ A $가 $ m \times n $ 크기이고, 행렬 $ B $가 $ n \times p $ 크기일 때, 행렬 곱 $ A \times B $의 결과는 $ m \times p $ 크기의 행렬이다. 곱셈 과정은 다음과 같다:
  $$
  (A \times B)_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}
  $$
  즉, $ A $의 i번째 행과 $ B $의 j번째 열에 해당하는 원소들을 곱하고, 그 결과를 더하여 새로운 행렬의 $ (i, j) $ 위치에 배치한다.

- **예시**:
  $$
  A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}
  $$
  $$
  A \times B = \begin{pmatrix} 1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\ 3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8 \end{pmatrix} = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
  $$

- **결과**: 새로운 **행렬**.

NumPy에서는 다음 세 가지 방법으로 행렬곱을 수행할 수 있다.
- @ 연산자: (a, b) @ (b, c) = (a, c)  -> 가장 기본적으로 사용
- np.matmul()
- np.dot() -> 2차원은 동일하나 다차원으로 올라가면 다르게 동작할 수 있으므로 사용 X

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a @ b, end="\n---\n")  # 행렬 곱셈 연산자
print(np.matmul(a, b), end="\n---\n")
print(np.dot(a, b), end="\n---\n")  # np.dot도 행렬 곱셈을 수행하지만, 1차원 배열에 대해서는 내적을 수행한다는 점에서 차이가 있다.

In [3]:
c = np.array([[1, 2]]) # (1, 2) 배열
d = np.array([[3], [4]]) # (2, 1) 배열
print(c.shape, d.shape)
x = c @ d  # (1, 2) @ (2, 1) -> (1, 1) 배열
print(x.shape, x)

(1, 2) (2, 1)
(1, 1) [[11]]


In [4]:
c = np.array([[1, 2, 3], [4, 5, 6]])       # (2, 3) 배열
d = np.array([[7, 8], [9, 10], [11, 12]])  # (3, 2) 배열
print(c.shape, d.shape)
x = c @ d  
print(x.shape, x)                          # (2, 2) 배열

(2, 3) (3, 2)
(2, 2) [[ 58  64]
 [139 154]]


In [6]:
c = np.array([[1, 2, 3], [4, 5, 6]])       # (2, 3) 배열
d = np.array([[7, 8, 9], [10, 11, 12]])    # (2, 3) 배열 -> (3, 2) 배열로 전치(transpose)하여 행렬 곱셈 가능
print(c.shape, d.shape)
# x = c @ d                                3과 2는 행렬 곱 불가 ValueError 발생     
# print(x.shape, x)                        # (2, 3) @ (3, 2) -> (2, 2) 배열

(2, 3) (2, 3)


## 기타 연산
Numpy는 배열 전체에 대해 다양한 수학 함수를 제공한다.

In [7]:
# 절대값
arr1 = np.array([[1, -2], [-3, 4]])
print(np.abs(arr1), end="\n---\n")

[[1 2]
 [3 4]]
---


In [ ]:
# 반올림
arr2 = np.array([[-1.234, 1.234, 2.345, 3.456, 4.567]])
print(np.round(arr2), end="\n---\n")  # 반올림
print(np.ceil(arr2), end="\n---\n")   # 올림
print(np.floor(arr2), end="\n---\n")  # 내림
print(np.trunc(arr2), end="\n---\n")  # 소수점 이하 버림(절삭)

### axis 속성
연산을 수행할 축을 지정한다.

- axis=0 : 행 방향으로 연산 (열 기준 연산)
- axis=1 : 열 방향으로 연산 (행 기준 연산)
- axis=None : 배열을 1차원으로 펼친 후 연산

axis는 "어느 방향으로 줄일것인가"를 의미

In [10]:
# min
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(arr))  # 전체 배열에서 최소값
print(arr.min())  # 배열 객체의 메서드로도 최소값 계산 가능, axis=None 이 기본 값으로 배열을 1차원으로 펼치고 최소값을 구함

print(arr.min(axis=0))  # 열 방향으로 최소값 계산 -> 각 열에서 최소값
print(arr.min(axis=1))  # 행 방향으로 최소값 계산 -> 각 행에서 최소값

1
1
[1 2 3]
[1 4]


In [11]:
# sum
print(arr.sum())  # 전체 배열의 합
print(arr.sum(axis=0))  # 열 방향으로 합 계산 -> 각 열의 합
print(arr.sum(axis=1))  # 행 방향으로 합 계산 -> 각 행의 합

21
[5 7 9]
[ 6 15]


In [12]:
# mean
print(arr.mean())  # 전체 배열의 평균
print(arr.mean(axis=0))  # 열 방향으로 평균 계산 -> 각 열의 평균
print(arr.mean(axis=1))  # 행 방향으로 평균 계산 -> 각 행의 평균

3.5
[2.5 3.5 4.5]
[2. 5.]
