# 통계 기초
NumPy 통계는 정식 통계분석 도구라기보다, 데이터를 빠르게 요약하고 분포를 감 잡기 위한 기초 연산이다.

In [1]:
import numpy as np

## 중심 경향 측도 (Central Tendency)
데이터의 대표적인 중심 값을 나타내는 통계 지표이다.
대표적으로 다음 세가지를 많이 사용한다.
- 평균(mean) : 모든 값의 합을 데티어 개수로 나눈 값
- 중앙값(median) : 데이터를 정렬했을 때 가운데 위치한 값
- 최빈값(mode) : 가장 많이 등장하는 값

In [2]:
# 학생들의 시험 점수
scores = np.array([85, 90, 92, 88, 90, 75, 88, 95, 92, 85, 80, 95, 100, 92, 85])

In [4]:
# 평균(Mean): 데이터의 전체적인 중심을 나타내는 가장 기본적인 통계값
print(f'합계: {np.sum(scores)}')
print(f'데이터 개수: {scores.size}')
print(f'평균: {np.mean(scores)}')

합계: 1332
데이터 개수: 15
평균: 88.8


In [5]:
# 중앙값(Median): 데이터를 정렬했을 때 가운데 위치한 값
# 홀수 -> 가운데 1개 값
# 짝수 -> 가운데 2개 값 평균
# 이상치(outlier)의 영향을 평균보다 덜 받는 특징
print(sorted(scores))  # 점수 정렬
print(f'중앙값: {np.median(scores)}')

[np.int64(75), np.int64(80), np.int64(85), np.int64(85), np.int64(85), np.int64(88), np.int64(88), np.int64(90), np.int64(90), np.int64(92), np.int64(92), np.int64(92), np.int64(95), np.int64(95), np.int64(100)]
중앙값: 90.0


In [9]:
# 최빈값(Mode): 데이터에서 가장 많이 등장하는 값
print(f'중복 제거한 값: {np.unique(scores)}')
values, counts = np.unique(scores, return_counts=True)
print(values, counts)

max_count = np.max(counts)
# 최대 빈도수와 같은 위치의 값만 선택
vals = values[counts == max_count]
print(f'최빈값: {vals}, 빈도수: {max_count}')

중복 제거한 값: [ 75  80  85  88  90  92  95 100]
[ 75  80  85  88  90  92  95 100] [1 1 3 2 2 3 2 1]
최빈값: [85 92], 빈도수: 3


## 산포 측도
데이터가 평균을 기준으로 얼마나 퍼져 있는지를 나타내는 지표이다.
대표적으로 다음 두 가지를 많이 사용한다.
- 분산(variance)
- 표준편차(standard deviation)

In [10]:
# 분산 : 데이터가 평균에서 얼마나 떨어져 있는지 나타내는 값
# 값이 클수록 데이터의 퍼짐 정도가 크다는 의미
# (값-평균)^2 의 평균
print(f'분산: {np.mean((scores - np.mean(scores)) ** 2)}')
print(f'표준편차: {np.std(scores)}')

분산: 36.559999999999995
표준편차: 6.046486583132389


In [12]:
# 표준편차 : 분산의 제곱근
# 데이터가 평균에서 얼마나 퍼져 있는지를 직관적으로 나타냄
print(f'표준편차: { np.sqrt(np.var(scores)) }')
print(f'표준편차: { np.std(scores) }')

표준편차: 6.046486583132389
표준편차: 6.046486583132389


## 모집단 vs 표본
분산과 표준편차는 계산 방식에 따라 두 가지가 있다.
- 모집단: 전체 데이터를 알고 있을 때
- 표본: 일부 데이터로 전체를 추정할 때

NumPy에서는 ddof 옵션으로 구분한다. (분산 계산 시 나누는 값을 조정)
- ddof=0: 모집단(default)
- ddof=1: 표본

In [ ]:
# 모집단 기준 계산
print(f'모집단 분산: { np.var(scores, ddof=0) }')
print(f'모집단 표준편차: { np.std(scores, ddof=0) }')
# 표본 기준 계산 (분산 계산 시 나누는 값을 n-1로 처리하므로 값이 약간 더 크게 나온다)
print(f'표본 분산: { np.var(scores, ddof=1) }')
print(f'표본 표준편차: { np.std(scores, ddof=1) }')

모집단 분산: 36.559999999999995
모집단 표준편차: 6.046486583132389
표본 분산: 39.17142857142857
표본 표준편차: 6.258708219067939


In [16]:
# 예시 데이터
values = np.array([12, 25, 8, 45, 33, 17, 29, 41])

# 합계, 최대, 최소
print(f'합계: {np.sum(values)}')
print(f'최대값: {np.max(values)}')
print(f'최소값: {np.min(values)}')

# 최대값, 최소값의 위치
print(f'최대값 위치: {np.argmax(values)}')
print(f'최소값 위치: {np.argmin(values)}')

# 범위 : 데이터의 전체 퍼짐 정도 (max - min)
print(f'범위: {np.ptp(values)}')

합계: 210
최대값: 45
최소값: 8
최대값 위치: 3
최소값 위치: 2
범위: 37


## 난수 생성 (Random Data)
Numpy는 다양한 확률 분포 기반의 난수 생성 함수를 제공한다.
대표적으로 다음 분포를 많이 사용한다.
- 정규분포(normal distribution)
- 균등분포(uniform distribution)
  
데이터 시뮬레이션이나 테스트 데이터 생성에 사용된다.

### 정규 분포
평균을 중심으로 좌우 대칭인 종 모양 분포이다.
Numpy에서는 np.random.normal() 함수로 생성한다.

In [17]:
# random.normal(loc, scale, size)
# loc 평균값, scale 표준편차, size 생성할 데이터 개수
arr = np.random.normal(0, 1, 100)
arr

array([-0.75502461, -0.19896258,  0.28013033, -1.58774565, -3.17699924,
       -0.60341836,  1.94200237,  0.69878686, -0.92771518, -1.40552753,
       -0.27983039, -1.26256001,  1.23821859,  0.99359807, -0.50599781,
        1.46930954,  0.89660127, -1.29236175,  1.53612157,  0.35526298,
        0.02270897,  0.21865314,  0.06221494,  0.26514293,  1.14271574,
        1.13662373,  0.57930103, -1.26248369,  0.3128948 ,  1.42086419,
       -0.85605629, -0.94348881,  0.40524608, -0.39020022, -0.42907617,
       -0.52655524, -0.92115991,  0.22247929, -0.26119775, -1.7641759 ,
        0.78075152, -1.19631751, -0.16157141,  0.92507013, -0.39886893,
       -0.05365125,  1.15747526, -0.32712342,  1.48077895, -0.01319838,
        0.84357706, -0.97463125, -1.84136344, -0.69681112,  1.00990364,
        1.10655913, -0.07506907,  0.66914134, -0.90260713,  0.8549696 ,
        0.68198038,  2.18856324,  1.50563818,  0.48632527,  0.66135365,
        0.29708018, -1.35430092,  0.7931342 ,  0.52221103,  1.61

### 표준 정규 분포
np.random.randn() 은 평균 0, 표준편차 1의 정규분포 데이터를 생성한다.

In [21]:
arr = np.random.randn(100)
arr = np.random.randn(5, 20)
arr

array([[ 1.95076821, -0.88363478,  1.91674035,  0.57128841,  1.26571128,
        -0.06317166,  1.6226372 ,  0.10612768,  0.24680487, -1.98634262,
         0.25795589, -0.94033204, -1.20173671,  0.45327803, -0.21737329,
         0.78080816,  0.05850419,  0.93410973, -0.88592396, -1.30821621],
       [ 1.04973092, -0.50361694,  0.8578042 ,  0.50597838, -0.6459297 ,
        -0.22553551,  0.48235298, -0.55517259,  1.68270545, -0.85279741,
        -0.1151688 , -1.17734341,  0.60697124, -0.34829154, -1.75025846,
         0.90422621, -2.01625745, -0.80622043,  0.71504803,  1.92723823],
       [ 0.65501259, -1.18559376, -0.05424689, -2.63682886,  1.41847238,
         0.3856902 ,  0.11142847, -1.37885896, -0.54072078, -0.44512995,
         1.32122884, -1.36835591, -0.27959517, -0.61582815,  0.28694589,
         0.27852241,  0.0620517 ,  0.97150257,  0.34193569,  0.2542736 ],
       [-0.72384902, -0.55130118,  0.24726506, -0.02787628, -1.38973704,
        -0.74599793,  0.25344884,  0.19090859,  

## 균등 분포
모든 값이 동일한 확률로 발생하는 분포이다.
- np.random.randint() : 지정한 범위에서 정수 난수를 생성한다.

In [22]:
# random.randint(low, high, size)
# low~high 범위의 size 개수 균등 분포 반환
arr = np.random.randint(1, 10, 1000)
arr

array([6, 5, 8, 7, 7, 3, 1, 1, 3, 3, 4, 8, 9, 1, 7, 5, 3, 8, 9, 3, 6, 4,
       2, 7, 7, 2, 4, 3, 3, 4, 2, 6, 9, 6, 8, 2, 3, 6, 6, 4, 3, 5, 3, 7,
       3, 6, 4, 7, 1, 2, 4, 2, 3, 5, 3, 4, 3, 3, 6, 7, 9, 9, 7, 2, 7, 3,
       8, 2, 5, 5, 7, 2, 8, 4, 3, 5, 3, 5, 2, 4, 2, 9, 8, 7, 3, 8, 6, 5,
       6, 3, 2, 3, 5, 4, 8, 4, 5, 3, 5, 1, 9, 3, 4, 2, 5, 6, 9, 5, 2, 3,
       8, 9, 4, 2, 6, 6, 5, 8, 1, 9, 1, 4, 1, 1, 3, 2, 1, 9, 1, 7, 6, 2,
       7, 7, 3, 3, 8, 2, 2, 8, 5, 5, 2, 3, 9, 2, 2, 2, 8, 5, 4, 1, 7, 1,
       9, 1, 4, 1, 4, 9, 4, 6, 8, 2, 5, 3, 6, 8, 4, 8, 3, 3, 7, 6, 7, 7,
       6, 1, 3, 8, 7, 4, 7, 3, 8, 6, 8, 8, 9, 7, 5, 9, 8, 8, 7, 4, 8, 2,
       4, 2, 8, 8, 1, 2, 5, 1, 4, 9, 9, 2, 6, 1, 4, 5, 8, 8, 1, 7, 2, 8,
       4, 8, 5, 7, 2, 6, 2, 4, 3, 7, 7, 7, 3, 1, 6, 1, 7, 8, 1, 9, 4, 8,
       2, 3, 1, 8, 3, 8, 3, 3, 2, 1, 5, 3, 6, 8, 8, 5, 5, 8, 8, 5, 2, 9,
       8, 2, 5, 5, 8, 9, 9, 3, 6, 4, 5, 4, 6, 8, 8, 6, 5, 2, 8, 9, 8, 3,
       1, 2, 9, 8, 5, 6, 5, 8, 6, 4, 6, 1, 9, 5, 2,

### np.random.rand() : 0~1 사이의 균등분포 실수 난수를 생성한다.

In [23]:
arr = np.random.rand(10, 10)
arr

array([[0.4799771 , 0.81364628, 0.87737825, 0.87006921, 0.12547731,
        0.24616773, 0.11657012, 0.15932441, 0.28848739, 0.21720839],
       [0.38393369, 0.17049378, 0.32947367, 0.19579688, 0.1283958 ,
        0.39079135, 0.86681375, 0.94234631, 0.15509218, 0.54817267],
       [0.82500285, 0.54358263, 0.93803264, 0.29869831, 0.01102691,
        0.6375214 , 0.1109308 , 0.16011771, 0.09608571, 0.09805867],
       [0.26790949, 0.02616424, 0.53188607, 0.97618104, 0.27976325,
        0.30567721, 0.38225301, 0.1139958 , 0.81806888, 0.23745533],
       [0.20570077, 0.02343749, 0.50392848, 0.03683791, 0.73429958,
        0.65081711, 0.14285503, 0.71527853, 0.67609429, 0.7586397 ],
       [0.93047843, 0.03950903, 0.82677373, 0.21834409, 0.9480149 ,
        0.13238369, 0.52924311, 0.08628188, 0.73722487, 0.662956  ],
       [0.98421229, 0.11865028, 0.16225533, 0.25583554, 0.78384632,
        0.07527329, 0.74174157, 0.13257387, 0.08075181, 0.44496378],
       [0.54947164, 0.45637282, 0.5939885

## seed
난수 생성의 재현성을 위해 seed 값을 고정할 수 있다.

In [ ]:
np.random.seed(0)  # 시드 설정(고정된 난수 생성) -> 재현 가능한 결과를 얻을 수 있음
np.random.rand(2, 3)  # 시드가 고정되어 동일한 난수(0~1 사잇값) 생성

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

## 샘플링
np.random.choice() 는 기존 데이터에서 무작위로 값을 선택할 때 사용한다.
옵션
- replace=True : 복원 추출
- replace=False : 비복원 추출

In [ ]:
arr = np.array([10, 3, 5, 7, 8, 9])
np.random.choice(arr)                         # 1개 추출
np.random.choice(arr, size=3)                 # 추출 개수 설정
np.random.choice(arr, size=3, replace=False)  # 중복 불허 비복원 추출

array([ 7, 10, 10])

In [162]:
# 확률 지정
probs = [0.8, 0.05, 0.05, 0.05, 0.025, 0.025]  # 확률은 1(100%)이 되어야 함
np.random.choice(arr, p=probs)  # 확률에 따라 값 추출

np.int64(10)