# narray 형태 변경

In [1]:
import numpy as np

## reshape()
배열의 shape를 변경한다.
- 전체 요소 개수는 반드시 동일해야 한다.
- `-1`을 사용하면 해당 차원의 크기를 자동 계산한다.

In [ ]:
arr = np.arange(12)
print(arr.reshape(2, 6), end="\n---\n")
print(arr.reshape(2, -1), end="\n---\n")
print(arr.reshape(3, 4), end="\n---\n")
print(arr.reshape(-1, 4))
# print(arr.reshape(3, 3))

## ravel()
다차원 배열을 **1차원 배열로 펼친다.**
- 원본 배열의 데이터를 공유하는 View를 반환할 수 있다.
- 따라서 반환 된 배열을 수정하면 **원본 배열도 영향을 받을 수 있다.**

In [ ]:
arr = np.random.randint(1, 10, (3, 4))
print(arr, end="\n---\n")

rav = np.ravel(arr)
print(rav, end="\n---\n")

rav[0] = 999
print(arr, end="\n---\n")
print(rav)

## flatten()
다차원 배열을 **1차원 배열로 변환한다.**
- 항상 **새로운 배열**을 반환한다.
- 반환 된 배열을 수정해도 원본 배열에는 영향이 없다.

In [ ]:
arr = np.random.randint(1, 10, (3, 4))
print(arr, end="\n---\n")

flat = arr.flatten()
print(flat, end="\n---\n")

flat[0] = 999
print(arr, end="\n---\n")
print(flat)

## expand_dims()

배열에 새로운 축(axis)를 추가하여 차원을 늘린다.

예
- (10,) -> (1, 10)
- (10,) -> (10, 1)

In [ ]:
arr = np.arange(1, 11)
print(arr, arr.shape, end="\n---\n")

# 행 축 추가
arr2 = np.expand_dims(arr, axis=0, end="\n---\n")
print(arr2, arr2.shape)

# 열 축 추가
arr3 = np.expand_dims(arr, axis=1)
print(arr3, arr3.shape)

## squeeze()
길이(크기)가 **1인 차원(axis)** 을 제거한다.

예
- (1, 10) -> (10,)
- (3, 1) -> (3,)

In [ ]:
arr = np.array([[1, 2, 3]])
print(arr, arr.shape, end="\n---\n")

arr2 = np.squeeze(arr, axis=0, end="\n---\n")
print(arr2, arr2.shape)

In [ ]:
arr = np.array([[1], [2], [3]])
print(arr, arr.shape, end="\n---\n")

arr2 = np.squeeze(arr, axis=1)
print(arr2, arr2.shape)

In [ ]:
# 3차원 배열
arr = np.array([[[1, 2, 3]]])
print(arr, arr.shape, end="\n---\n")

arr2 = np.squeeze(arr, axis=0)
print(arr2, arr2.shape, end="\n---\n")

arr3 = np.squeeze(arr, axis=1)
print(arr3, arr3.shape)

## transpose()
배열의 **축(axis)을 교환** 한다.
2차원 배열에서는 행과 열을 서로 바꾸는 **전치 행렬** 이 된다.
3차원 이상에서는 축의 순서를 바꾸는 연산이다. (axis의 순서를 뒤집는다)

In [ ]:
# 전치 행렬 : 기존 행렬에서 행과 열을 교환한 행렬
# 정방(정사각) 행렬 예제
arr = np.array([[1, 2], [3, 4]])
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
print("---")

# 전치 - 세 방법은 모두 동일한 결과를 반환한다.
print(np.transpose(arr))
print("---")
print(arr.transpose())
print("---")
print(arr.T)


In [3]:
# 직사각행렬
arr = np.arange(1, 7).reshape(2, 3)
print(arr, arr.shape)
print("---")

print(arr.T, arr.T.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
---
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [4]:
# 행렬곱은 앞 행렬의 열 개수와 뒤 행렬의 행 개수가 같아야 한다.
# 따라서 transpose 를 통해 shape를 맞춰주는 경우가 많다.
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(1, 7).reshape(2, 3)

# print(arr1 @ arr2)  # (2, 3) @ (2, 3)
print(arr1 @ arr2.T)  # (2, 3) @ (3, 2)
print("---")
print(arr1.T @ arr2)  # (3, 2) @ (2, 3)

[[14 32]
 [32 77]]
---
[[17 22 27]
 [22 29 36]
 [27 36 45]]
