# numpy_practice1_solution

In [1]:
import numpy as np

sales = np.array([
    [12, 15, 14, 10, 13],
    [ 9, 11, 10, 12,  8],
    [14, 13, 16, 15, 17]
])

prices = np.array([1800, 2000, 2200])

sales

array([[12, 15, 14, 10, 13],
       [ 9, 11, 10, 12,  8],
       [14, 13, 16, 15, 17]])

## 1. ndarray 기본 확인
1) sales의 shape, ndim, size, dtype를 확인하시오.
2) prices의 shape를 확인하시오.

In [2]:
print(sales.shape)
print(sales.ndim)
print(sales.size)
print(sales.dtype)

print(prices.shape)

(3, 5)
2
15
int64
(3,)


## 2. 배열 생성
1) 길이가 5인 0 배열을 만드시오.
2) 3 x 5 형태의 1 배열을 만드시오.
3) 모든 값이 7인 2 x 3 배열을 만드시오.
4) 0부터 9까지의 값을 가지는 1차원 배열을 만드시오.

In [4]:
print(np.zeros(5))
print(np.ones((3, 5)))
print(np.full((2, 3), 7))
print(np.arange(10))

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[0 1 2 3 4 5 6 7 8 9]


## 3. 인덱싱
1) 첫 번째 지점의 첫째 날 판매량을 선택하시오.
2) 세 번째 지점의 넷째 날 판매량을 선택하시오.
3) 마지막 지점의 마지막 날 판매량을 음수 인덱스로 선택하시오.

In [5]:
print(sales[0, 0])
print(sales[2, 3])
print(sales[-1, -1])

12
15
17


## 4. 슬라이싱
1) 첫 번째 지점의 전체 판매량을 선택하시오.
2) 모든 지점의 첫 3일 판매량을 선택하시오.
3) 두 번째와 세 번째 지점만 선택하시오.

In [6]:
print(sales[0])
print(sales[:, :3])
print(sales[1:3])

[12 15 14 10 13]
[[12 15 14]
 [ 9 11 10]
 [14 13 16]]
[[ 9 11 10 12  8]
 [14 13 16 15 17]]


## 5. Fancy Indexing
첫째 날과 셋째 날 판매량만 모든 지점에서 선택하시오.

In [8]:
sales[:, [0, 2]]

array([[12, 14],
       [ 9, 10],
       [14, 16]])

## 6. Boolean Indexing
1) 판매량이 13 이상인 값만 선택하시오.
2) sales에서 10 미만인 값의 개수를 구하시오.

In [9]:
print(sales[sales >= 13])
print((sales < 10).sum())

[15 14 13 14 13 16 15 17]
2


## 7. 기본 연산
1) sales에 2를 더하시오.
2) sales에 2를 곱하시오.
3) sales와 같은 shape의 discount 배열을 만든 뒤 더하시오.
   discount = np.array([[0,1,0,1,0],[1,0,1,0,1],[0,0,1,1,0]])

In [10]:
print(sales + 2)
print(sales * 2)

discount = np.array([
    [0, 1, 0, 1, 0],
    [1, 0, 1, 0, 1],
    [0, 0, 1, 1, 0]
])

print(sales + discount)

[[14 17 16 12 15]
 [11 13 12 14 10]
 [16 15 18 17 19]]
[[24 30 28 20 26]
 [18 22 20 24 16]
 [28 26 32 30 34]]
[[12 16 14 11 13]
 [10 11 11 12  9]
 [14 13 17 16 17]]


## 8. Broadcasting
지점별 가격 prices를 sales에 곱해서 revenue 배열을 만드시오.
힌트: sales는 판매량, prices는 지점별 단가이다.

In [12]:
revenue = sales * prices.reshape(3, 1)
revenue

array([[21600, 27000, 25200, 18000, 23400],
       [18000, 22000, 20000, 24000, 16000],
       [30800, 28600, 35200, 33000, 37400]])

## 9. 수학 함수
revenue 배열에서
1) 전체 합계
2) 지점별 합계
3) 날짜별 합계
를 구하시오.

In [13]:
print(revenue.sum())
print(revenue.sum(axis=1))
print(revenue.sum(axis=0))

380200
[115200 100000 165000]
[70400 77600 80400 75000 76800]


## 10. 행렬곱
아래 promo 배열은 날짜별 행사 가중치이다.
sales와 promo를 행렬곱하여 지점별 행사 점수를 구하시오.

In [15]:
# 행렬곱은 각 값에 가중치를 곱한 뒤 모두 더해서 하나의 결과를 만드는 계산
# 5일치 판매량에 날짜별 중요도를 반영해서 지점별 총 점수를 구하는 과정
promo = np.array([1.0, 0.8, 1.2, 1.1, 0.9])

sales @ promo

array([63.5, 50.2, 75.4])

## 11. 통계 기본
sales 배열에서
1) 평균
2) 중앙값
3) 최댓값
4) 최솟값
을 구하시오.

In [ ]:
print(sales.mean())         
print(np.median(sales))     # 배열 메소드로 없음
print(sales.max())
print(sales.min())

12.6
13.0
17
8


## 12. 축 기준 통계
1) 지점별 평균 판매량
2) 날짜별 평균 판매량
3) 지점별 표준편차
를 구하시오.

In [17]:
print(sales.mean(axis=1))
print(sales.mean(axis=0))
print(sales.std(axis=1))

[12.8 10.  15. ]
[11.66666667 13.         13.33333333 12.33333333 12.66666667]
[1.72046505 1.41421356 1.41421356]


## 13. 난수와 통계
평균 100, 표준편차 10인 고객 방문 수 데이터를 30개 생성하시오.
그리고 평균과 표준편차를 구하시오.

In [19]:
np.random.seed(42)
visits = np.random.normal(100, 10, 30)
visits.mean(), visits.std()

(np.float64(98.11853104148962), np.float64(8.848791915963048))

## 14. 종합 문제
아래 inventory는 지점별 현재 재고이다.
1) 예상 판매량 sales와 비교해 부족한 재고 위치를 True/False로 구하시오.
2) 부족한 위치의 개수를 구하시오.
3) 부족한 위치의 판매량 값만 선택하시오.

In [22]:
inventory = np.array([
    [15, 14, 15, 12, 10],
    [10, 10,  9, 13,  9],
    [13, 13, 15, 14, 16]
])

lack = inventory < sales
print(lack)
print(lack.sum())
print(sales[lack])

[[False  True False False  True]
 [False  True  True False False]
 [ True False  True  True  True]]
8
[15 13 11 10 14 16 15 17]
